Add hooks to roll
pyroll-project/pyroll-core pull request #119
Opened 2023-11-15 13:18 UTC by ChRen95

Added more Hooks to roll and roll_pass.
Especially neutral_point, angle as well as entry angle to have this implemented never the less the plugin that one is using.

2023-11-15 13:19 UTC, ChRen95 commented
Afterwards we should consider a new release.

2023-11-16 07:19 UTC, axtimhaus requested changes

2023-11-16 07:19 UTC, axtimhaus commented on pyroll/core/roll_pass/hookimpls/roll.py
> +        return None
```suggestion
```

2023-11-16 07:19 UTC, axtimhaus commented on pyroll/core/roll_pass/hookimpls/roll.py
> +        return None
```suggestion
```

2023-11-16 07:19 UTC, axtimhaus commented on pyroll/core/roll_pass/hookimpls/roll.py
>          if self.has_value("neutral_point"):
```suggestion
        if self.has_value("neutral_angle"):
```

2023-11-16 07:19 UTC, axtimhaus commented on pyroll/core/roll_pass/hookimpls/roll_pass.py
>      if self.roll.has_value("neutral_point"):
```suggestion
    if self.roll.has_value("neutral_angle"):
```

2023-11-16 07:19 UTC, axtimhaus commented on pyroll/core/roll_pass/hookimpls/roll.py
> +    if self.has_value("neutral_angle"):
```suggestion
    if self.has_set_or_cached("neutral_angle"):
```

2023-11-16 07:54 UTC, ChRen95 commented
Updated according to changes, ready for merging

2023-11-17 12:25 UTC, axtimhaus approved these changes

2023-11-17 12:26 UTC, merged