Power Hooks
pyroll-project/pyroll-core pull request #86
Opened 2023-08-23 07:22 UTC by axtimhaus

Closes #85 

Energy consumption requires density!

2023-08-25 06:42 UTC, ChRen95 commented on pyroll/core/unit/hookimpls.py
> +@Unit.volume_throughput
Should be named volume_flux

2023-08-25 06:43 UTC, ChRen95 commented on pyroll/core/unit/unit.py
> +    volume_throughput = Hook[float]()
Isn't really a volume, so either include standard length of 1 or we should think about renaming

2023-08-25 06:46 UTC, ChRen95 requested changes
Should rename Hook Volume Throughput to Volume Flux since this is generally used in literature.

2023-08-28 07:15 UTC, axtimhaus commented
Should name the mass and volume flux equally.
Throughput is also a valid term, but more from the economical point of view. But I agree with using flux.

2023-08-29 06:24 UTC, ChRen95 approved these changes

2023-08-29 06:25 UTC, merged